<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="4" failures="0" hostname="DESKTOP-3BP8FB9" name="pytest" skipped="0" tests="4" time="1.255" timestamp="2020-12-06T18:37:07.652588"><testcase classname="" file="test_civic_jabber_ingest/test_cli.py" name="test_civic_jabber_ingest.test_cli" time="0.000"><error message="collection failure">ImportError while importing test module &apos;C:\Users\Kevin\Desktop\Projects\data-ingest\test_civic_jabber_ingest\test_cli.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\anaconda3\lib\site-packages\_pytest\python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
..\..\..\anaconda3\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
..\..\..\anaconda3\lib\site-packages\_pytest\assertion\rewrite.py:143: in exec_module
    exec(co, module.__dict__)
test_civic_jabber_ingest\test_cli.py:4: in &lt;module&gt;
    import civic_jabber_ingest.cli as cli
civic_jabber_ingest\cli.py:5: in &lt;module&gt;
    from civic_jabber_ingest.external_services.newspaper import load_news
civic_jabber_ingest\external_services\newspaper.py:5: in &lt;module&gt;
    import newspaper
E   ModuleNotFoundError: No module named &apos;newspaper&apos;</error></testcase><testcase classname="" file="test_civic_jabber_ingest/external_services/test_newspaper.py" name="test_civic_jabber_ingest.external_services.test_newspaper" time="0.000"><error message="collection failure">ImportError while importing test module &apos;C:\Users\Kevin\Desktop\Projects\data-ingest\test_civic_jabber_ingest\external_services\test_newspaper.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\anaconda3\lib\site-packages\_pytest\python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
..\..\..\anaconda3\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
..\..\..\anaconda3\lib\site-packages\_pytest\assertion\rewrite.py:143: in exec_module
    exec(co, module.__dict__)
test_civic_jabber_ingest\external_services\test_newspaper.py:1: in &lt;module&gt;
    import newspaper
E   ModuleNotFoundError: No module named &apos;newspaper&apos;</error></testcase><testcase classname="" file="test_civic_jabber_ingest/external_services/test_open_states_api.py" name="test_civic_jabber_ingest.external_services.test_open_states_api" time="0.000"><error message="collection failure">ImportError while importing test module &apos;C:\Users\Kevin\Desktop\Projects\data-ingest\test_civic_jabber_ingest\external_services\test_open_states_api.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\anaconda3\lib\site-packages\_pytest\python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
..\..\..\anaconda3\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
..\..\..\anaconda3\lib\site-packages\_pytest\assertion\rewrite.py:143: in exec_module
    exec(co, module.__dict__)
test_civic_jabber_ingest\external_services\test_open_states_api.py:4: in &lt;module&gt;
    import civic_jabber_ingest.external_services.open_states as open_states
civic_jabber_ingest\external_services\open_states.py:10: in &lt;module&gt;
    import civic_jabber_ingest.utils.database as db
civic_jabber_ingest\utils\database.py:3: in &lt;module&gt;
    import psycopg2
E   ModuleNotFoundError: No module named &apos;psycopg2&apos;</error></testcase><testcase classname="" file="test_civic_jabber_ingest/utils/test_database.py" name="test_civic_jabber_ingest.utils.test_database" time="0.000"><error message="collection failure">ImportError while importing test module &apos;C:\Users\Kevin\Desktop\Projects\data-ingest\test_civic_jabber_ingest\utils\test_database.py&apos;.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\anaconda3\lib\site-packages\_pytest\python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
..\..\..\anaconda3\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
..\..\..\anaconda3\lib\site-packages\_pytest\assertion\rewrite.py:143: in exec_module
    exec(co, module.__dict__)
test_civic_jabber_ingest\utils\test_database.py:5: in &lt;module&gt;
    import psycopg2
E   ModuleNotFoundError: No module named &apos;psycopg2&apos;</error></testcase></testsuite></testsuites>